apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: web
  name: web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/ifontlabs/pacman-nginx-app:latest
        name: web
        ports:
        - containerPort: 80
          name: http-server
